-- CURATED + RAW DDL for AI Price Intelligence
-- Idempotent CREATE IF NOT EXISTS.

USE DATABASE AI_PRICE_INTEL;

-- ---------------------------------------------------------------------------
-- RAW landing
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS RAW.LOAD_BATCH (
  BATCH_ID            VARCHAR NOT NULL,
  SOURCE_NAME         VARCHAR NOT NULL,
  LOADED_AT           TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  ROW_COUNT           NUMBER,
  STATUS              VARCHAR,
  MESSAGE             VARCHAR
);

CREATE TABLE IF NOT EXISTS RAW.DIM_PROVIDER (
  PROVIDER_ID         VARCHAR,
  NAME                VARCHAR,
  TYPE                VARCHAR,
  WEBSITE             VARCHAR,
  BATCH_ID            VARCHAR,
  LOADED_AT           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RAW.DIM_MODEL (
  MODEL_ID            VARCHAR,
  PROVIDER_ID         VARCHAR,
  MODEL_NAME          VARCHAR,
  FAMILY              VARCHAR,
  MODALITY            VARCHAR,
  CONTEXT_WINDOW_TOKENS NUMBER,
  MAX_OUTPUT_TOKENS   NUMBER,
  SUPPORTS_TOOLS      BOOLEAN,
  SUPPORTS_VISION     BOOLEAN,
  LICENSE             VARCHAR,
  RELEASE_DATE        DATE,
  DEPRECATION_DATE    DATE,
  IS_ACTIVE           BOOLEAN,
  BATCH_ID            VARCHAR,
  LOADED_AT           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RAW.FACT_MODEL_PRICE (
  MODEL_ID            VARCHAR,
  PRICE_INPUT_USD_PER_1M_TOKENS NUMBER(18,6),
  PRICE_OUTPUT_USD_PER_1M_TOKENS NUMBER(18,6),
  PRICE_CACHED_INPUT_USD_PER_1M_TOKENS NUMBER(18,6),
  BATCH_DISCOUNT_PCT  NUMBER(9,4),
  TIER_NOTES          VARCHAR,
  SOURCE_URL          VARCHAR,
  RETRIEVED_AT        TIMESTAMP_NTZ,
  BATCH_ID            VARCHAR,
  LOADED_AT           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RAW.FACT_BENCHMARK (
  MODEL_ID            VARCHAR,
  BENCHMARK_NAME      VARCHAR,
  SCORE               NUMBER(18,6),
  SCORE_TYPE          VARCHAR,
  EVAL_DATE           DATE,
  SOURCE_URL          VARCHAR,
  RETRIEVED_AT        TIMESTAMP_NTZ,
  BATCH_ID            VARCHAR,
  LOADED_AT           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RAW.DIM_GPU_INSTANCE (
  INSTANCE_ID         VARCHAR,
  CLOUD               VARCHAR,
  INSTANCE_NAME       VARCHAR,
  GPU_MODEL           VARCHAR,
  GPU_COUNT           NUMBER,
  VRAM_GB             NUMBER,
  REGION_SCOPE        VARCHAR,
  BATCH_ID            VARCHAR,
  LOADED_AT           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RAW.FACT_GPU_PRICE (
  INSTANCE_ID         VARCHAR,
  REGION              VARCHAR,
  PRICE_ON_DEMAND_USD_HR NUMBER(18,6),
  PRICE_SPOT_USD_HR   NUMBER(18,6),
  PRICE_1YR_RESERVED_USD_HR NUMBER(18,6),
  SOURCE_URL          VARCHAR,
  RETRIEVED_AT        TIMESTAMP_NTZ,
  BATCH_ID            VARCHAR,
  LOADED_AT           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RAW.FACT_CORTEX_PRICE (
  FUNCTION_NAME       VARCHAR,
  MODEL_NAME          VARCHAR,
  CREDITS_PER_1M_TOKENS NUMBER(18,6),
  SOURCE_URL          VARCHAR,
  RETRIEVED_AT        TIMESTAMP_NTZ,
  BATCH_ID            VARCHAR,
  LOADED_AT           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ---------------------------------------------------------------------------
-- CURATED dimensions / facts
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS CURATED.DIM_PROVIDER (
  PROVIDER_ID         VARCHAR NOT NULL,
  NAME                VARCHAR NOT NULL,
  TYPE                VARCHAR NOT NULL,
  WEBSITE             VARCHAR,
  UPDATED_AT          TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_DIM_PROVIDER PRIMARY KEY (PROVIDER_ID)
);

CREATE TABLE IF NOT EXISTS CURATED.DIM_MODEL (
  MODEL_ID            VARCHAR NOT NULL,
  PROVIDER_ID         VARCHAR NOT NULL,
  MODEL_NAME          VARCHAR NOT NULL,
  FAMILY              VARCHAR,
  MODALITY            VARCHAR,
  CONTEXT_WINDOW_TOKENS NUMBER,
  MAX_OUTPUT_TOKENS   NUMBER,
  SUPPORTS_TOOLS      BOOLEAN,
  SUPPORTS_VISION     BOOLEAN,
  LICENSE             VARCHAR,
  RELEASE_DATE        DATE,
  DEPRECATION_DATE    DATE,
  IS_ACTIVE           BOOLEAN DEFAULT TRUE,
  UPDATED_AT          TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_DIM_MODEL PRIMARY KEY (MODEL_ID)
);

CREATE TABLE IF NOT EXISTS CURATED.FACT_MODEL_PRICE_HISTORY (
  MODEL_ID            VARCHAR NOT NULL,
  PRICE_INPUT_USD_PER_1M_TOKENS NUMBER(18,6),
  PRICE_OUTPUT_USD_PER_1M_TOKENS NUMBER(18,6),
  PRICE_CACHED_INPUT_USD_PER_1M_TOKENS NUMBER(18,6),
  BATCH_DISCOUNT_PCT  NUMBER(9,4),
  TIER_NOTES          VARCHAR,
  VALID_FROM          TIMESTAMP_NTZ NOT NULL,
  VALID_TO            TIMESTAMP_NTZ,
  IS_CURRENT          BOOLEAN NOT NULL DEFAULT TRUE,
  SOURCE_URL          VARCHAR NOT NULL,
  RETRIEVED_AT        TIMESTAMP_NTZ NOT NULL,
  ROW_HASH            VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS CURATED.FACT_BENCHMARK_SCORE (
  MODEL_ID            VARCHAR NOT NULL,
  BENCHMARK_NAME      VARCHAR NOT NULL,
  SCORE               NUMBER(18,6) NOT NULL,
  SCORE_TYPE          VARCHAR NOT NULL,
  EVAL_DATE           DATE,
  SOURCE_URL          VARCHAR NOT NULL,
  RETRIEVED_AT        TIMESTAMP_NTZ NOT NULL,
  UPDATED_AT          TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS CURATED.DIM_GPU_INSTANCE (
  INSTANCE_ID         VARCHAR NOT NULL,
  CLOUD               VARCHAR NOT NULL,
  INSTANCE_NAME       VARCHAR NOT NULL,
  GPU_MODEL           VARCHAR,
  GPU_COUNT           NUMBER,
  VRAM_GB             NUMBER,
  REGION_SCOPE        VARCHAR,
  UPDATED_AT          TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_DIM_GPU PRIMARY KEY (INSTANCE_ID)
);

CREATE TABLE IF NOT EXISTS CURATED.FACT_GPU_PRICE_HISTORY (
  INSTANCE_ID         VARCHAR NOT NULL,
  REGION              VARCHAR NOT NULL,
  PRICE_ON_DEMAND_USD_HR NUMBER(18,6),
  PRICE_SPOT_USD_HR   NUMBER(18,6),
  PRICE_1YR_RESERVED_USD_HR NUMBER(18,6),
  VALID_FROM          TIMESTAMP_NTZ NOT NULL,
  VALID_TO            TIMESTAMP_NTZ,
  IS_CURRENT          BOOLEAN NOT NULL DEFAULT TRUE,
  SOURCE_URL          VARCHAR NOT NULL,
  RETRIEVED_AT        TIMESTAMP_NTZ NOT NULL,
  ROW_HASH            VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS CURATED.FACT_CORTEX_PRICE_HISTORY (
  FUNCTION_NAME       VARCHAR NOT NULL,
  MODEL_NAME          VARCHAR NOT NULL,
  CREDITS_PER_1M_TOKENS NUMBER(18,6) NOT NULL,
  VALID_FROM          TIMESTAMP_NTZ NOT NULL,
  VALID_TO            TIMESTAMP_NTZ,
  IS_CURRENT          BOOLEAN NOT NULL DEFAULT TRUE,
  SOURCE_URL          VARCHAR NOT NULL,
  RETRIEVED_AT        TIMESTAMP_NTZ NOT NULL,
  ROW_HASH            VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS CURATED._META_REFRESH_LOG (
  REFRESH_ID          VARCHAR NOT NULL,
  STARTED_AT          TIMESTAMP_NTZ NOT NULL,
  FINISHED_AT         TIMESTAMP_NTZ,
  STATUS              VARCHAR NOT NULL,
  ROWS_UPSERTED       VARIANT,
  MESSAGE             VARCHAR,
  CONSTRAINT PK_META_REFRESH PRIMARY KEY (REFRESH_ID)
);
