-- Consumer-facing secure views in SHARE (also useful in CURATED for ops).
USE DATABASE AI_PRICE_INTEL;

-- Current-price convenience views (CURATED, non-secure for provider ops)
CREATE OR REPLACE VIEW CURATED.VW_MODEL_CURRENT AS
SELECT
  m.MODEL_ID,
  m.PROVIDER_ID,
  p.NAME AS PROVIDER_NAME,
  m.MODEL_NAME,
  m.FAMILY,
  m.MODALITY,
  m.CONTEXT_WINDOW_TOKENS,
  m.MAX_OUTPUT_TOKENS,
  m.SUPPORTS_TOOLS,
  m.SUPPORTS_VISION,
  m.LICENSE,
  m.IS_ACTIVE,
  h.PRICE_INPUT_USD_PER_1M_TOKENS,
  h.PRICE_OUTPUT_USD_PER_1M_TOKENS,
  h.PRICE_CACHED_INPUT_USD_PER_1M_TOKENS,
  h.BATCH_DISCOUNT_PCT,
  h.TIER_NOTES,
  h.VALID_FROM,
  h.SOURCE_URL,
  h.RETRIEVED_AT
FROM CURATED.DIM_MODEL m
JOIN CURATED.DIM_PROVIDER p ON p.PROVIDER_ID = m.PROVIDER_ID
JOIN CURATED.FACT_MODEL_PRICE_HISTORY h
  ON h.MODEL_ID = m.MODEL_ID AND h.IS_CURRENT = TRUE;

CREATE OR REPLACE VIEW CURATED.VW_GPU_CURRENT AS
SELECT
  g.INSTANCE_ID,
  g.CLOUD,
  g.INSTANCE_NAME,
  g.GPU_MODEL,
  g.GPU_COUNT,
  g.VRAM_GB,
  h.REGION,
  h.PRICE_ON_DEMAND_USD_HR,
  h.PRICE_SPOT_USD_HR,
  h.PRICE_1YR_RESERVED_USD_HR,
  h.VALID_FROM,
  h.SOURCE_URL,
  h.RETRIEVED_AT
FROM CURATED.DIM_GPU_INSTANCE g
JOIN CURATED.FACT_GPU_PRICE_HISTORY h
  ON h.INSTANCE_ID = g.INSTANCE_ID AND h.IS_CURRENT = TRUE;

CREATE OR REPLACE VIEW CURATED.VW_CORTEX_CURRENT AS
SELECT
  FUNCTION_NAME,
  MODEL_NAME,
  CREDITS_PER_1M_TOKENS,
  VALID_FROM,
  SOURCE_URL,
  RETRIEVED_AT
FROM CURATED.FACT_CORTEX_PRICE_HISTORY
WHERE IS_CURRENT = TRUE;

CREATE OR REPLACE VIEW CURATED.VW_PRICE_CHANGES_90D AS
WITH ordered AS (
  SELECT
    MODEL_ID,
    PRICE_INPUT_USD_PER_1M_TOKENS,
    PRICE_OUTPUT_USD_PER_1M_TOKENS,
    VALID_FROM,
    VALID_TO,
    IS_CURRENT,
    SOURCE_URL,
    LAG(PRICE_INPUT_USD_PER_1M_TOKENS) OVER (PARTITION BY MODEL_ID ORDER BY VALID_FROM) AS PREV_INPUT,
    LAG(PRICE_OUTPUT_USD_PER_1M_TOKENS) OVER (PARTITION BY MODEL_ID ORDER BY VALID_FROM) AS PREV_OUTPUT
  FROM CURATED.FACT_MODEL_PRICE_HISTORY
)
SELECT
  MODEL_ID,
  VALID_FROM AS CHANGED_AT,
  PREV_INPUT AS OLD_INPUT_USD_PER_1M,
  PRICE_INPUT_USD_PER_1M_TOKENS AS NEW_INPUT_USD_PER_1M,
  CASE
    WHEN PREV_INPUT IS NULL OR PREV_INPUT = 0 THEN NULL
    ELSE ROUND(100 * (PRICE_INPUT_USD_PER_1M_TOKENS - PREV_INPUT) / PREV_INPUT, 2)
  END AS INPUT_PCT_CHANGE,
  PREV_OUTPUT AS OLD_OUTPUT_USD_PER_1M,
  PRICE_OUTPUT_USD_PER_1M_TOKENS AS NEW_OUTPUT_USD_PER_1M,
  CASE
    WHEN PREV_OUTPUT IS NULL OR PREV_OUTPUT = 0 THEN NULL
    ELSE ROUND(100 * (PRICE_OUTPUT_USD_PER_1M_TOKENS - PREV_OUTPUT) / PREV_OUTPUT, 2)
  END AS OUTPUT_PCT_CHANGE,
  SOURCE_URL
FROM ordered
WHERE PREV_INPUT IS NOT NULL
  AND VALID_FROM >= DATEADD('day', -90, CURRENT_TIMESTAMP());

CREATE OR REPLACE VIEW CURATED.VW_COST_PER_BENCHMARK_POINT AS
SELECT
  c.MODEL_ID,
  c.MODEL_NAME,
  c.PROVIDER_NAME,
  c.PRICE_INPUT_USD_PER_1M_TOKENS,
  c.PRICE_OUTPUT_USD_PER_1M_TOKENS,
  b.BENCHMARK_NAME,
  b.SCORE,
  b.SCORE_TYPE,
  CASE
    WHEN b.SCORE IS NULL OR b.SCORE = 0 THEN NULL
    ELSE ROUND(c.PRICE_INPUT_USD_PER_1M_TOKENS / b.SCORE, 6)
  END AS INPUT_USD_PER_BENCHMARK_POINT,
  CASE
    WHEN b.SCORE IS NULL OR b.SCORE = 0 THEN NULL
    ELSE ROUND(
      (COALESCE(c.PRICE_INPUT_USD_PER_1M_TOKENS, 0) + COALESCE(c.PRICE_OUTPUT_USD_PER_1M_TOKENS, 0))
        / b.SCORE,
      6
    )
  END AS BLENDED_USD_PER_BENCHMARK_POINT
FROM CURATED.VW_MODEL_CURRENT c
JOIN CURATED.FACT_BENCHMARK_SCORE b
  ON b.MODEL_ID = c.MODEL_ID
 AND UPPER(b.BENCHMARK_NAME) = 'MMLU';

-- ---------------------------------------------------------------------------
-- SHARE secure views (Marketplace surface)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE SECURE VIEW SHARE.DIM_PROVIDER AS
SELECT PROVIDER_ID, NAME, TYPE, WEBSITE, UPDATED_AT
FROM CURATED.DIM_PROVIDER;

CREATE OR REPLACE SECURE VIEW SHARE.DIM_MODEL AS
SELECT
  MODEL_ID, PROVIDER_ID, MODEL_NAME, FAMILY, MODALITY,
  CONTEXT_WINDOW_TOKENS, MAX_OUTPUT_TOKENS, SUPPORTS_TOOLS, SUPPORTS_VISION,
  LICENSE, RELEASE_DATE, DEPRECATION_DATE, IS_ACTIVE, UPDATED_AT
FROM CURATED.DIM_MODEL;

CREATE OR REPLACE SECURE VIEW SHARE.FACT_MODEL_PRICE_HISTORY AS
SELECT
  MODEL_ID,
  PRICE_INPUT_USD_PER_1M_TOKENS,
  PRICE_OUTPUT_USD_PER_1M_TOKENS,
  PRICE_CACHED_INPUT_USD_PER_1M_TOKENS,
  BATCH_DISCOUNT_PCT,
  TIER_NOTES,
  VALID_FROM,
  VALID_TO,
  IS_CURRENT,
  SOURCE_URL,
  RETRIEVED_AT
FROM CURATED.FACT_MODEL_PRICE_HISTORY;

CREATE OR REPLACE SECURE VIEW SHARE.FACT_BENCHMARK_SCORE AS
SELECT MODEL_ID, BENCHMARK_NAME, SCORE, SCORE_TYPE, EVAL_DATE, SOURCE_URL, RETRIEVED_AT
FROM CURATED.FACT_BENCHMARK_SCORE;

CREATE OR REPLACE SECURE VIEW SHARE.DIM_GPU_INSTANCE AS
SELECT INSTANCE_ID, CLOUD, INSTANCE_NAME, GPU_MODEL, GPU_COUNT, VRAM_GB, REGION_SCOPE, UPDATED_AT
FROM CURATED.DIM_GPU_INSTANCE;

CREATE OR REPLACE SECURE VIEW SHARE.FACT_GPU_PRICE_HISTORY AS
SELECT
  INSTANCE_ID, REGION,
  PRICE_ON_DEMAND_USD_HR, PRICE_SPOT_USD_HR, PRICE_1YR_RESERVED_USD_HR,
  VALID_FROM, VALID_TO, IS_CURRENT, SOURCE_URL, RETRIEVED_AT
FROM CURATED.FACT_GPU_PRICE_HISTORY;

CREATE OR REPLACE SECURE VIEW SHARE.FACT_CORTEX_PRICE_HISTORY AS
SELECT
  FUNCTION_NAME, MODEL_NAME, CREDITS_PER_1M_TOKENS,
  VALID_FROM, VALID_TO, IS_CURRENT, SOURCE_URL, RETRIEVED_AT
FROM CURATED.FACT_CORTEX_PRICE_HISTORY;

CREATE OR REPLACE SECURE VIEW SHARE.VW_MODEL_CURRENT AS
SELECT * FROM CURATED.VW_MODEL_CURRENT;

CREATE OR REPLACE SECURE VIEW SHARE.VW_GPU_CURRENT AS
SELECT * FROM CURATED.VW_GPU_CURRENT;

CREATE OR REPLACE SECURE VIEW SHARE.VW_CORTEX_CURRENT AS
SELECT * FROM CURATED.VW_CORTEX_CURRENT;

CREATE OR REPLACE SECURE VIEW SHARE.VW_PRICE_CHANGES_90D AS
SELECT * FROM CURATED.VW_PRICE_CHANGES_90D;

CREATE OR REPLACE SECURE VIEW SHARE.VW_COST_PER_BENCHMARK_POINT AS
SELECT * FROM CURATED.VW_COST_PER_BENCHMARK_POINT;

CREATE OR REPLACE SECURE VIEW SHARE.VW_META_REFRESH_LOG AS
SELECT REFRESH_ID, STARTED_AT, FINISHED_AT, STATUS, ROWS_UPSERTED, MESSAGE
FROM CURATED._META_REFRESH_LOG;
