-- Marketplace share definition (provider account).
-- Adjust ACCOUNT identifiers before running in production.

USE DATABASE AI_PRICE_INTEL;

CREATE SHARE IF NOT EXISTS AI_PRICE_INTEL_SHARE
  COMMENT = 'AI Model & Compute Price Intelligence — Marketplace data share';

GRANT USAGE ON DATABASE AI_PRICE_INTEL TO SHARE AI_PRICE_INTEL_SHARE;
GRANT USAGE ON SCHEMA AI_PRICE_INTEL.SHARE TO SHARE AI_PRICE_INTEL_SHARE;

GRANT SELECT ON VIEW AI_PRICE_INTEL.SHARE.DIM_PROVIDER TO SHARE AI_PRICE_INTEL_SHARE;
GRANT SELECT ON VIEW AI_PRICE_INTEL.SHARE.DIM_MODEL TO SHARE AI_PRICE_INTEL_SHARE;
GRANT SELECT ON VIEW AI_PRICE_INTEL.SHARE.FACT_MODEL_PRICE_HISTORY TO SHARE AI_PRICE_INTEL_SHARE;
GRANT SELECT ON VIEW AI_PRICE_INTEL.SHARE.FACT_BENCHMARK_SCORE TO SHARE AI_PRICE_INTEL_SHARE;
GRANT SELECT ON VIEW AI_PRICE_INTEL.SHARE.DIM_GPU_INSTANCE TO SHARE AI_PRICE_INTEL_SHARE;
GRANT SELECT ON VIEW AI_PRICE_INTEL.SHARE.FACT_GPU_PRICE_HISTORY TO SHARE AI_PRICE_INTEL_SHARE;
GRANT SELECT ON VIEW AI_PRICE_INTEL.SHARE.FACT_CORTEX_PRICE_HISTORY TO SHARE AI_PRICE_INTEL_SHARE;
GRANT SELECT ON VIEW AI_PRICE_INTEL.SHARE.VW_MODEL_CURRENT TO SHARE AI_PRICE_INTEL_SHARE;
GRANT SELECT ON VIEW AI_PRICE_INTEL.SHARE.VW_GPU_CURRENT TO SHARE AI_PRICE_INTEL_SHARE;
GRANT SELECT ON VIEW AI_PRICE_INTEL.SHARE.VW_CORTEX_CURRENT TO SHARE AI_PRICE_INTEL_SHARE;
GRANT SELECT ON VIEW AI_PRICE_INTEL.SHARE.VW_PRICE_CHANGES_90D TO SHARE AI_PRICE_INTEL_SHARE;
GRANT SELECT ON VIEW AI_PRICE_INTEL.SHARE.VW_COST_PER_BENCHMARK_POINT TO SHARE AI_PRICE_INTEL_SHARE;
GRANT SELECT ON VIEW AI_PRICE_INTEL.SHARE.VW_META_REFRESH_LOG TO SHARE AI_PRICE_INTEL_SHARE;

-- Example private share for QA (uncomment and set account):
-- ALTER SHARE AI_PRICE_INTEL_SHARE ADD ACCOUNTS = <ORG>.<ACCOUNT>;
