-- Quality checks. Each query returns FAIL rows; zero rows = pass.
-- Invoked by ingestion/load_snowflake.py after MERGE.
-- NOTE: Do not gate on prior SUCCESS log age — that bricks the refresh that
-- would clear staleness. Freshness is enforced via current-row RETRIEVED_AT.

USE DATABASE AI_PRICE_INTEL;

-- 1) Dimensions non-empty
SELECT 'DIM_PROVIDER_EMPTY' AS CHECK_NAME, COUNT(*) AS FAIL_COUNT
FROM CURATED.DIM_PROVIDER
HAVING COUNT(*) = 0;

SELECT 'DIM_MODEL_EMPTY' AS CHECK_NAME, COUNT(*) AS FAIL_COUNT
FROM CURATED.DIM_MODEL
HAVING COUNT(*) = 0;

-- 2) Current prices exist
SELECT 'MODEL_CURRENT_EMPTY' AS CHECK_NAME, COUNT(*) AS FAIL_COUNT
FROM CURATED.FACT_MODEL_PRICE_HISTORY
WHERE IS_CURRENT = TRUE
HAVING COUNT(*) = 0;

-- 3) Referential: model prices point at known models
SELECT 'ORPHAN_MODEL_PRICE' AS CHECK_NAME, COUNT(*) AS FAIL_COUNT
FROM CURATED.FACT_MODEL_PRICE_HISTORY h
LEFT JOIN CURATED.DIM_MODEL m ON m.MODEL_ID = h.MODEL_ID
WHERE m.MODEL_ID IS NULL
HAVING COUNT(*) > 0;

-- 4) No overlapping current rows per model
SELECT 'MULTI_CURRENT_MODEL_PRICE' AS CHECK_NAME, COUNT(*) AS FAIL_COUNT
FROM (
  SELECT MODEL_ID, COUNT(*) AS C
  FROM CURATED.FACT_MODEL_PRICE_HISTORY
  WHERE IS_CURRENT = TRUE
  GROUP BY 1
  HAVING COUNT(*) > 1
)
HAVING COUNT(*) > 0;

-- 5) Provenance required
SELECT 'MISSING_PROVENANCE_MODEL' AS CHECK_NAME, COUNT(*) AS FAIL_COUNT
FROM CURATED.FACT_MODEL_PRICE_HISTORY
WHERE SOURCE_URL IS NULL OR TRIM(SOURCE_URL) = '' OR RETRIEVED_AT IS NULL
HAVING COUNT(*) > 0;

SELECT 'MISSING_PROVENANCE_GPU' AS CHECK_NAME, COUNT(*) AS FAIL_COUNT
FROM CURATED.FACT_GPU_PRICE_HISTORY
WHERE SOURCE_URL IS NULL OR TRIM(SOURCE_URL) = '' OR RETRIEVED_AT IS NULL
HAVING COUNT(*) > 0;

SELECT 'MISSING_PROVENANCE_CORTEX' AS CHECK_NAME, COUNT(*) AS FAIL_COUNT
FROM CURATED.FACT_CORTEX_PRICE_HISTORY
WHERE SOURCE_URL IS NULL OR TRIM(SOURCE_URL) = '' OR RETRIEVED_AT IS NULL
HAVING COUNT(*) > 0;

-- 6) Current model prices should have been retrieved within 14 days
--    (passes on the refresh that just wrote fresh retrieved_at values)
SELECT 'STALE_MODEL_PRICES' AS CHECK_NAME, 1 AS FAIL_COUNT
FROM (
  SELECT MAX(RETRIEVED_AT) AS LAST_RETRIEVED
  FROM CURATED.FACT_MODEL_PRICE_HISTORY
  WHERE IS_CURRENT = TRUE
) t
WHERE LAST_RETRIEVED IS NOT NULL
  AND LAST_RETRIEVED < DATEADD('day', -14, CURRENT_TIMESTAMP());

-- 7) Negative prices
SELECT 'NEGATIVE_MODEL_PRICE' AS CHECK_NAME, COUNT(*) AS FAIL_COUNT
FROM CURATED.FACT_MODEL_PRICE_HISTORY
WHERE COALESCE(PRICE_INPUT_USD_PER_1M_TOKENS, 0) < 0
   OR COALESCE(PRICE_OUTPUT_USD_PER_1M_TOKENS, 0) < 0
HAVING COUNT(*) > 0;

SELECT 'NEGATIVE_GPU_PRICE' AS CHECK_NAME, COUNT(*) AS FAIL_COUNT
FROM CURATED.FACT_GPU_PRICE_HISTORY
WHERE COALESCE(PRICE_ON_DEMAND_USD_HR, 0) < 0
HAVING COUNT(*) > 0;
