-- Cortex Cost Advisor setup (read-only app)
-- ACCOUNT_USAGE views are created/refreshed via ENSURE_ACCOUNT_USAGE_VIEWS()
-- so they work after the consumer grants IMPORTED PRIVILEGES (post-install).

CREATE APPLICATION ROLE IF NOT EXISTS APP_USER;

CREATE OR ALTER VERSIONED SCHEMA APP_SCHEMA;
GRANT USAGE ON SCHEMA APP_SCHEMA TO APPLICATION ROLE APP_USER;

-- ---------------------------------------------------------------------------
-- Reference callback (optional Marketplace dataset binding)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE APP_SCHEMA.REGISTER_REFERENCE(
  REF_NAME STRING,
  OPERATION STRING,
  REF_OR_ALIAS STRING
)
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
  CASE (OPERATION)
    WHEN 'ADD' THEN
      SELECT SYSTEM$SET_REFERENCE(:REF_NAME, :REF_OR_ALIAS);
    WHEN 'REMOVE' THEN
      SELECT SYSTEM$REMOVE_REFERENCE(:REF_NAME);
    WHEN 'CLEAR' THEN
      SELECT SYSTEM$REMOVE_ALL_REFERENCES();
    ELSE
      RETURN 'UNKNOWN_OPERATION';
  END CASE;
  RETURN 'OK';
END;
$$;

GRANT USAGE ON PROCEDURE APP_SCHEMA.REGISTER_REFERENCE(STRING, STRING, STRING)
  TO APPLICATION ROLE APP_USER;

-- ---------------------------------------------------------------------------
-- Recreate ACCOUNT_USAGE wrappers (safe to call after privilege grant)
-- Prefer CORTEX_AI_FUNCTIONS_USAGE_HISTORY; fall back to CORTEX_AISQL_USAGE_HISTORY.
-- Never use deprecated CORTEX_FUNCTIONS_USAGE_HISTORY (data ended 2025-11-21).
-- ---------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE APP_SCHEMA.ENSURE_ACCOUNT_USAGE_VIEWS()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
  source_used VARCHAR DEFAULT 'PENDING_PRIVILEGES';
BEGIN
  -- Cortex usage (primary -> fallback -> empty placeholder until privileges are granted)
  BEGIN
    CREATE OR REPLACE VIEW APP_SCHEMA.V_CORTEX_USAGE AS
    SELECT
      START_TIME AS USAGE_TIME,
      FUNCTION_NAME,
      MODEL_NAME,
      COALESCE(
        (
          SELECT SUM(f.VALUE:"value"::NUMBER)
          FROM TABLE(FLATTEN(INPUT => m.METRICS)) f
          WHERE LOWER(f.VALUE:"key":"unit"::STRING) = 'tokens'
        ),
        0
      ) AS TOKENS,
      CREDITS AS TOKEN_CREDITS
    FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_AI_FUNCTIONS_USAGE_HISTORY m
    WHERE START_TIME >= DATEADD('day', -365, CURRENT_TIMESTAMP());
    source_used := 'CORTEX_AI_FUNCTIONS_USAGE_HISTORY';
  EXCEPTION
    WHEN OTHER THEN
      BEGIN
        CREATE OR REPLACE VIEW APP_SCHEMA.V_CORTEX_USAGE AS
        SELECT
          USAGE_TIME,
          FUNCTION_NAME,
          MODEL_NAME,
          COALESCE(TOKENS, 0) AS TOKENS,
          COALESCE(TOKEN_CREDITS, 0) AS TOKEN_CREDITS
        FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_AISQL_USAGE_HISTORY
        WHERE USAGE_TIME >= DATEADD('day', -365, CURRENT_TIMESTAMP());
        source_used := 'CORTEX_AISQL_USAGE_HISTORY';
      EXCEPTION
        WHEN OTHER THEN
          CREATE OR REPLACE VIEW APP_SCHEMA.V_CORTEX_USAGE AS
          SELECT
            CAST(NULL AS TIMESTAMP_LTZ) AS USAGE_TIME,
            CAST(NULL AS VARCHAR) AS FUNCTION_NAME,
            CAST(NULL AS VARCHAR) AS MODEL_NAME,
            CAST(NULL AS NUMBER) AS TOKENS,
            CAST(NULL AS NUMBER) AS TOKEN_CREDITS
          WHERE 1 = 0;
          source_used := 'PENDING_PRIVILEGES';
      END;
  END;

  -- Metering fallback (AI_SERVICES / Cortex-related)
  BEGIN
    CREATE OR REPLACE VIEW APP_SCHEMA.V_METERING_HISTORY AS
    SELECT
      START_TIME,
      END_TIME,
      SERVICE_TYPE,
      CREDITS_USED,
      CREDITS_USED_COMPUTE,
      CREDITS_USED_CLOUD_SERVICES
    FROM SNOWFLAKE.ACCOUNT_USAGE.METERING_HISTORY
    WHERE START_TIME >= DATEADD('day', -365, CURRENT_TIMESTAMP())
      AND (
        UPPER(SERVICE_TYPE) LIKE '%CORTEX%'
        OR UPPER(SERVICE_TYPE) LIKE '%AI_SERVICES%'
        OR UPPER(SERVICE_TYPE) = 'AI_SERVICES'
      );
  EXCEPTION
    WHEN OTHER THEN
      CREATE OR REPLACE VIEW APP_SCHEMA.V_METERING_HISTORY AS
      SELECT
        CAST(NULL AS TIMESTAMP_LTZ) AS START_TIME,
        CAST(NULL AS TIMESTAMP_LTZ) AS END_TIME,
        CAST(NULL AS VARCHAR) AS SERVICE_TYPE,
        CAST(NULL AS NUMBER) AS CREDITS_USED,
        CAST(NULL AS NUMBER) AS CREDITS_USED_COMPUTE,
        CAST(NULL AS NUMBER) AS CREDITS_USED_CLOUD_SERVICES
      WHERE 1 = 0;
  END;

  GRANT SELECT ON VIEW APP_SCHEMA.V_CORTEX_USAGE TO APPLICATION ROLE APP_USER;
  GRANT SELECT ON VIEW APP_SCHEMA.V_METERING_HISTORY TO APPLICATION ROLE APP_USER;

  RETURN source_used;
END;
$$;

GRANT USAGE ON PROCEDURE APP_SCHEMA.ENSURE_ACCOUNT_USAGE_VIEWS()
  TO APPLICATION ROLE APP_USER;

-- ---------------------------------------------------------------------------
-- Consumer planning prefs (credit $/rate for USD estimates). Stays in-app only.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS APP_SCHEMA.USER_SETTINGS (
  SETTING_KEY VARCHAR PRIMARY KEY,
  SETTING_VALUE VARCHAR,
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

GRANT SELECT, INSERT, UPDATE ON TABLE APP_SCHEMA.USER_SETTINGS TO APPLICATION ROLE APP_USER;

-- Best-effort create at install (may stub until privileges are granted).
-- Streamlit calls ENSURE_ACCOUNT_USAGE_VIEWS() again on each session.
CALL APP_SCHEMA.ENSURE_ACCOUNT_USAGE_VIEWS();

-- Streamlit UI (consumer sets query warehouse in Snowsight if needed)
CREATE OR REPLACE STREAMLIT APP_SCHEMA.CORTEX_COST_ADVISOR
  FROM '/src/streamlit'
  MAIN_FILE = 'main.py';

GRANT USAGE ON STREAMLIT APP_SCHEMA.CORTEX_COST_ADVISOR TO APPLICATION ROLE APP_USER;
